version: "2.0"

services:
  web:
    build: .
    command: docker build .
    ports:
      - "3001:3000"
    links:
      - mongo
  mongo:
    image: mongo:latest
    user: mongodb
    expose:
      - "27017"