apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blinklocationclaim
  labels:
    app: blink-location
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
